databases:
  - name: myweb-db
    databaseName: myweb
    user: myweb
    plan: free

services:
  - type: web
    name: myweb
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myweb-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
    region: singapore # or ohio, frankfurt, oregon
    plan: free
